/**
 * Multi-Language and Localization Support Dictionary
 */

export type LanguageCode = 'en' | 'es' | 'ar' | 'fr' | 'bn' | 'hi' | 'vi';

export interface LanguageItem {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  flag: string;
  dir: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageItem[] = [
  { code: 'en', label: 'English', nativeLabel: 'English (US)', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', label: 'French', nativeLabel: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية', flag: '🇦🇪', dir: 'rtl' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇧🇩', dir: 'ltr' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'vi', label: 'Vietnamese', nativeLabel: 'Tiếng Việt', flag: '🇻🇳', dir: 'ltr' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.accounts': 'My Accounts',
    'nav.deposit': 'Deposit',
    'nav.withdrawal': 'Withdrawal',
    'nav.transfer': 'Transfer',
    'nav.transactions': 'Transactions',
    'nav.wallet': 'Crypto Wallet',
    'nav.orders': 'Order History',
    'nav.performance': 'Performance',
    'nav.analytics': 'Market Analytics',
    'nav.copyTrading': 'Copy Trading',
    'nav.support': 'Support Hub',
    'nav.referrals': 'Invite & Earn',
    'nav.settings': 'Settings',
    'header.totalBalance': 'Total Balance',
    'header.quickTerminal': 'Web Terminal',
    'header.notifications': 'Notifications',
    'header.profile': 'Profile & Security',
    'header.signOut': 'Sign Out',
    'dashboard.welcome': 'Welcome back',
    'dashboard.equity': 'Equity',
    'dashboard.freeMargin': 'Free Margin',
    'dashboard.floatingPL': 'Floating P&L',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.openAccount': 'Open Account',
    'dashboard.activeAccounts': 'Active Accounts',
    'dashboard.recentActivity': 'Recent Activity',
    'accounts.real': 'Real Accounts',
    'accounts.demo': 'Demo Accounts',
    'accounts.archived': 'Archived',
    'accounts.openNew': 'Open New Account',
    'accounts.trade': 'Trade',
    'accounts.details': 'Account Details',
    'common.deposit': 'Deposit',
    'common.withdraw': 'Withdraw',
    'common.transfer': 'Transfer',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.submit': 'Submit',
    'common.status': 'Status',
    'common.amount': 'Amount',
    'common.success': 'Success',
    'common.loading': 'Loading...',
  },
  es: {
    'nav.dashboard': 'Panel Principal',
    'nav.accounts': 'Mis Cuentas',
    'nav.deposit': 'Depósito',
    'nav.withdrawal': 'Retiro',
    'nav.transfer': 'Transferencia',
    'nav.transactions': 'Transacciones',
    'nav.wallet': 'Billetera Cripto',
    'nav.orders': 'Historial de Órdenes',
    'nav.performance': 'Rendimiento',
    'nav.analytics': 'Análisis de Mercado',
    'nav.copyTrading': 'Copy Trading',
    'nav.support': 'Centro de Ayuda',
    'nav.referrals': 'Invita y Gana',
    'nav.settings': 'Configuración',
    'header.totalBalance': 'Saldo Total',
    'header.quickTerminal': 'Terminal Web',
    'header.notifications': 'Notificaciones',
    'header.profile': 'Perfil y Seguridad',
    'header.signOut': 'Cerrar Sesión',
    'dashboard.welcome': 'Bienvenido de nuevo',
    'dashboard.equity': 'Equidad',
    'dashboard.freeMargin': 'Margen Libre',
    'dashboard.floatingPL': 'P&L Flotante',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.openAccount': 'Abrir Cuenta',
    'dashboard.activeAccounts': 'Cuentas Activas',
    'dashboard.recentActivity': 'Actividad Reciente',
    'accounts.real': 'Cuentas Reales',
    'accounts.demo': 'Cuentas Demo',
    'accounts.archived': 'Archivadas',
    'accounts.openNew': 'Abrir Nueva Cuenta',
    'accounts.trade': 'Operar',
    'accounts.details': 'Detalles de Cuenta',
    'common.deposit': 'Depositar',
    'common.withdraw': 'Retirar',
    'common.transfer': 'Transferir',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.submit': 'Enviar',
    'common.status': 'Estado',
    'common.amount': 'Monto',
    'common.success': 'Éxito',
    'common.loading': 'Cargando...',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.accounts': 'Mes Comptes',
    'nav.deposit': 'Dépôt',
    'nav.withdrawal': 'Retrait',
    'nav.transfer': 'Transfert',
    'nav.transactions': 'Transactions',
    'nav.wallet': 'Portefeuille Crypto',
    'nav.orders': 'Historique des ordres',
    'nav.performance': 'Performance',
    'nav.analytics': 'Analyses Marché',
    'nav.copyTrading': 'Copy Trading',
    'nav.support': 'Support & Aide',
    'nav.referrals': 'Parrainage',
    'nav.settings': 'Paramètres',
    'header.totalBalance': 'Solde Total',
    'header.quickTerminal': 'Terminal Web',
    'header.notifications': 'Notifications',
    'header.profile': 'Profil & Sécurité',
    'header.signOut': 'Déconnexion',
    'dashboard.welcome': 'Bon retour',
    'dashboard.equity': 'Fonds Propres',
    'dashboard.freeMargin': 'Marge Libre',
    'dashboard.floatingPL': 'P&L Latent',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.openAccount': 'Ouvrir un Compte',
    'dashboard.activeAccounts': 'Comptes Actifs',
    'dashboard.recentActivity': 'Activité Récente',
    'accounts.real': 'Comptes Réels',
    'accounts.demo': 'Comptes Démo',
    'accounts.archived': 'Archivés',
    'accounts.openNew': 'Nouveau Compte',
    'accounts.trade': 'Trader',
    'accounts.details': 'Détails du Compte',
    'common.deposit': 'Déposer',
    'common.withdraw': 'Retirer',
    'common.transfer': 'Transférer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.submit': 'Valider',
    'common.status': 'Statut',
    'common.amount': 'Montant',
    'common.success': 'Succès',
    'common.loading': 'Chargement...',
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.accounts': 'حساباتي',
    'nav.deposit': 'إيداع',
    'nav.withdrawal': 'سحب',
    'nav.transfer': 'تحويل داخلي',
    'nav.transactions': 'سجل المعاملات',
    'nav.wallet': 'المحفظة الرقمية',
    'nav.orders': 'سجل الأوامر',
    'nav.performance': 'الأداء والتحليلات',
    'nav.analytics': 'تحليلات السوق',
    'nav.copyTrading': 'نسخ التداول',
    'nav.support': 'مركز الدعم',
    'nav.referrals': 'برنامج الإحالة',
    'nav.settings': 'الإعدادات',
    'header.totalBalance': 'الرصيد الإجمالي',
    'header.quickTerminal': 'المنصة الإلكترونية',
    'header.notifications': 'الإشعارات',
    'header.profile': 'الملف الشخصي والأمان',
    'header.signOut': 'تسجيل الخروج',
    'dashboard.welcome': 'مرحباً بك مجدداً',
    'dashboard.equity': 'صافي السيولة',
    'dashboard.freeMargin': 'الهامش المتاح',
    'dashboard.floatingPL': 'الأرباح والخسائر العائمة',
    'dashboard.quickActions': 'الإجراءات السريعة',
    'dashboard.openAccount': 'فتح حساب جديد',
    'dashboard.activeAccounts': 'الحسابات النشطة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'accounts.real': 'حسابات حقيقية',
    'accounts.demo': 'حسابات تجريبية',
    'accounts.archived': 'الأرشيف',
    'accounts.openNew': 'فتح حساب جديد',
    'accounts.trade': 'تداول',
    'accounts.details': 'تفاصيل الحساب',
    'common.deposit': 'إيداع',
    'common.withdraw': 'سحب',
    'common.transfer': 'تحويل',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.submit': 'إرسال',
    'common.status': 'الحالة',
    'common.amount': 'المبلغ',
    'common.success': 'تم بنجاح',
    'common.loading': 'جاري التحميل...',
  },
  bn: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.accounts': 'আমার অ্যাকাউন্টস',
    'nav.deposit': 'ডিপোজিট',
    'nav.withdrawal': 'উইথড্রয়াল',
    'nav.transfer': 'ট্রান্সফার',
    'nav.transactions': 'লেনদেনসমূহ',
    'nav.wallet': 'ক্রিপ্টো ওয়ালেট',
    'nav.orders': 'অর্ডার হিস্টোরি',
    'nav.performance': 'পারফরম্যান্স',
    'nav.analytics': 'মার্কেট অ্যানালিটিক্স',
    'nav.copyTrading': 'কপি ট্রেডিং',
    'nav.support': 'সাপোর্ট হাব',
    'nav.referrals': 'ইনভাইট ও আর্ন',
    'nav.settings': 'সেটিংস',
    'header.totalBalance': 'মোট ব্যালেন্স',
    'header.quickTerminal': 'ওয়েব টার্মিনাল',
    'header.notifications': 'নোটিফিকেশন',
    'header.profile': 'প্রোফাইল ও সিকিউরিটি',
    'header.signOut': 'সাইন আউট',
    'dashboard.welcome': 'স্বাগতম',
    'dashboard.equity': 'ইকুইটি',
    'dashboard.freeMargin': 'ফ্রি মার্জিন',
    'dashboard.floatingPL': 'ফ্লোটিং পি&এল',
    'dashboard.quickActions': 'দ্রুত অ্যাকশন',
    'dashboard.openAccount': 'অ্যাকাউন্ট খুলুন',
    'dashboard.activeAccounts': 'সক্রিয় অ্যাকাউন্টসমূহ',
    'dashboard.recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'accounts.real': 'রিয়েল অ্যাকাউন্ট',
    'accounts.demo': 'ডেমো অ্যাকাউন্ট',
    'accounts.archived': 'আর্কাইভড',
    'accounts.openNew': 'নতুন অ্যাকাউন্ট খুলুন',
    'accounts.trade': 'ট্রেড করুন',
    'accounts.details': 'অ্যাকাউন্ট বিবরণ',
    'common.deposit': 'জমা দিন',
    'common.withdraw': 'উত্তোলন করুন',
    'common.transfer': 'ট্রান্সফার',
    'common.cancel': 'বাতিল',
    'common.confirm': 'নিশ্চিত করুন',
    'common.submit': 'সাবমিট',
    'common.status': 'স্ট্যাটাস',
    'common.amount': 'পরিমাণ',
    'common.success': 'সফল',
    'common.loading': 'লোড হচ্ছে...',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.accounts': 'मेरे खाते',
    'nav.deposit': 'जमा करें',
    'nav.withdrawal': 'निकासी',
    'nav.transfer': 'ट्रांसफर',
    'nav.transactions': 'लेन-देन',
    'nav.wallet': 'क्रिप्टो वॉलेट',
    'nav.orders': 'ऑर्डर इतिहास',
    'nav.performance': 'प्रदर्शन',
    'nav.analytics': 'बाज़ार विश्लेषण',
    'nav.copyTrading': 'कॉपी ट्रेडिंग',
    'nav.support': 'सहायता केंद्र',
    'nav.referrals': 'रेफरल और कमाई',
    'nav.settings': 'सेटिंग्स',
    'header.totalBalance': 'कुल शेष राशि',
    'header.quickTerminal': 'वेब टर्मिनल',
    'header.notifications': 'सूचनाएं',
    'header.profile': 'प्रोफ़ाइल और सुरक्षा',
    'header.signOut': 'साइन आउट',
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.equity': 'इक्विटी',
    'dashboard.freeMargin': 'फ्री मार्जिन',
    'dashboard.floatingPL': 'फ्लोटिंग पीएंडएल',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.openAccount': 'खाता खोलें',
    'dashboard.activeAccounts': 'सक्रिय खाते',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    'accounts.real': 'रियल खाते',
    'accounts.demo': 'डेमो खाते',
    'accounts.archived': 'संग्रहीत',
    'accounts.openNew': 'नया खाता खोलें',
    'accounts.trade': 'ट्रेड करें',
    'accounts.details': 'खाता विवरण',
    'common.deposit': 'डिपॉजिट',
    'common.withdraw': 'निकासी',
    'common.transfer': 'ट्रांसफर',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.submit': 'जमा करें',
    'common.status': 'स्थिति',
    'common.amount': 'राशि',
    'common.success': 'सफल',
    'common.loading': 'लोड हो रहा है...',
  },
  vi: {
    'nav.dashboard': 'Bảng điều khiển',
    'nav.accounts': 'Tài khoản của tôi',
    'nav.deposit': 'Nạp tiền',
    'nav.withdrawal': 'Rút tiền',
    'nav.transfer': 'Chuyển nội bộ',
    'nav.transactions': 'Lịch sử giao dịch',
    'nav.wallet': 'Ví Tiền điện tử',
    'nav.orders': 'Lịch sử lệnh',
    'nav.performance': 'Hiệu suất',
    'nav.analytics': 'Phân tích thị trường',
    'nav.copyTrading': 'Copy Trading',
    'nav.support': 'Hỗ trợ khách hàng',
    'nav.referrals': 'Giới thiệu & Nhận thưởng',
    'nav.settings': 'Cài đặt',
    'header.totalBalance': 'Tổng số dư',
    'header.quickTerminal': 'Web Terminal',
    'header.notifications': 'Thông báo',
    'header.profile': 'Hồ sơ & Bảo mật',
    'header.signOut': 'Đăng xuất',
    'dashboard.welcome': 'Chào mừng trở lại',
    'dashboard.equity': 'Vốn chủ sở hữu',
    'dashboard.freeMargin': 'Ký quỹ khả dụng',
    'dashboard.floatingPL': 'Lãi/Lỗ thả nổi',
    'dashboard.quickActions': 'Thao tác nhanh',
    'dashboard.openAccount': 'Mở tài khoản',
    'dashboard.activeAccounts': 'Tài khoản hoạt động',
    'dashboard.recentActivity': 'Hoạt động gần đây',
    'accounts.real': 'Tài khoản Real',
    'accounts.demo': 'Tài khoản Demo',
    'accounts.archived': 'Lưu trữ',
    'accounts.openNew': 'Mở tài khoản mới',
    'accounts.trade': 'Giao dịch',
    'accounts.details': 'Chi tiết tài khoản',
    'common.deposit': 'Nạp',
    'common.withdraw': 'Rút',
    'common.transfer': 'Chuyển tiền',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.submit': 'Gửi',
    'common.status': 'Trạng thái',
    'common.amount': 'Số tiền',
    'common.success': 'Thành công',
    'common.loading': 'Đang tải...',
  }
};
